block.101 = minecraft:water minecraft:flowing_water

#ifdef IRIS_TAG_SUPPORT
  block.104 = %minecraft:leaves %minecraft:flowers %minecraft:tall_flowers minecraft:short_grass %minecraft:cave_vines minecraft:moss_block  minecraft:pale_moss_block minecraft:vine minecraft:pale_hanging_moss minecraft:pale_moss_carpet minecraft:bamboo minecraft:tall_grass minecraft:kelp minecraft:large_fern minecraft:fern minecraft:bush minecraft:bamboo_leaf minecraft:seagrass minecraft:tall_seagrass minecraft:packed_ice minecraft:blue_ice minecraft:snow minecraft:snow_block minecraft:powder_snow
  block.10003 = minecraft:torch minecraft:wall_torch minecraft:lantern minecraft:redstone_lamp:lit=true minecraft:glowstone minecraft:lava minecraft:lava_flow minecraft:fire minecraft:campfire minecraft:ocre_froglight minecraft:copper_bulb:lit=true minecraft:waxed_copper_bulb:lit=true minecraft:exposed_copper_bulb:lit=true minecraft:waxed_exposed_copper_bulb:lit=true %minecraft:candles minecraft:magma_block
  block.10004 = minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_fire minecraft:soul_lantern minecraft:soul_campfire
  block.10005 = minecraft:sea_lantern minecraft:sea_pickle minecraft:end_rod
  block.10006 = minecraft:redstone_block minecraft:redstone_torch minecraft:redstone_wall_torch
  block.10007 = minecraft:amethyst_cluster minecraft:amethyst_cluster minecraft:amethyst_cluster minecraft:medium_amethyst_bud minecraft:large_amethyst_bud minecraft:crying_obsidian minecraft:nether_portal minecraft:pearlescent_froglight
  block.10008 = minecraft:glow_lichen minecraft:copper_torch minecraft:copper_wall_torch minecraft:copper_lantern minecraft:waxed_copper_lantern minecraft:exposed_copper_lantern minecraft:waxed_exposed_copper_lantern minecraft:weathered_copper_lantern minecraft:waxed_weathered_copper_lantern minecraft:oxidized_copper_lantern minecraft:waxed_oxidized_copper_lantern minecraft:verdant_froglight
#endif

block.10000 = minecraft:grass_block
block.10001 = minecraft:dirt





